# use_frameworks!

platform :ios, '8.0'

target 'LWReachabilityManager_Example' do
  pod 'LWReachabilityManager', :path => '../'

  target 'LWReachabilityManager_Tests' do
    inherit! :search_paths

    
  end
end
